class GithubRepositorySaver
  def call(repository_data:)
    attributes = map_repository_attributes(repository_data)
    repository = GithubRepository.find_or_initialize_by(id: attributes[:id])
    repository.update!(attributes.except(:id))
    repository
  end

  private

  def map_repository_attributes(data)
    {
      id: data["id"],
      node_id: data["node_id"],
      name: data["name"],
      full_name: data["full_name"],
      owner_id: data.dig("owner", "id"),
      private: data["private"],
      html_url: data["html_url"],
      description: data["description"],
      fork: data["fork"],
      url: data["url"],
      forks_url: data["forks_url"],
      keys_url: data["keys_url"],
      collaborators_url: data["collaborators_url"],
      teams_url: data["teams_url"],
      hooks_url: data["hooks_url"],
      issue_events_url: data["issue_events_url"],
      events_url: data["events_url"],
      assignees_url: data["assignees_url"],
      branches_url: data["branches_url"],
      tags_url: data["tags_url"],
      blobs_url: data["blobs_url"],
      git_tags_url: data["git_tags_url"],
      git_refs_url: data["git_refs_url"],
      trees_url: data["trees_url"],
      statuses_url: data["statuses_url"],
      languages_url: data["languages_url"],
      stargazers_url: data["stargazers_url"],
      contributors_url: data["contributors_url"],
      subscribers_url: data["subscribers_url"],
      subscription_url: data["subscription_url"],
      commits_url: data["commits_url"],
      git_commits_url: data["git_commits_url"],
      comments_url: data["comments_url"],
      issue_comment_url: data["issue_comment_url"],
      contents_url: data["contents_url"],
      compare_url: data["compare_url"],
      merges_url: data["merges_url"],
      archive_url: data["archive_url"],
      downloads_url: data["downloads_url"],
      issues_url: data["issues_url"],
      pulls_url: data["pulls_url"],
      milestones_url: data["milestones_url"],
      notifications_url: data["notifications_url"],
      labels_url: data["labels_url"],
      releases_url: data["releases_url"],
      deployments_url: data["deployments_url"],
      pushed_at: data["pushed_at"],
      github_created_at: data["created_at"],
      github_updated_at: data["updated_at"],
      git_url: data["git_url"],
      ssh_url: data["ssh_url"],
      clone_url: data["clone_url"],
      svn_url: data["svn_url"],
      homepage: data["homepage"],
      size: data["size"],
      stargazers_count: data["stargazers_count"],
      watchers_count: data["watchers_count"],
      language: data["language"],
      has_issues: data["has_issues"],
      has_projects: data["has_projects"],
      has_downloads: data["has_downloads"],
      has_wiki: data["has_wiki"],
      has_pages: data["has_pages"],
      has_discussions: data["has_discussions"],
      forks_count: data["forks_count"],
      mirror_url: data["mirror_url"],
      archived: data["archived"],
      disabled: data["disabled"],
      open_issues_count: data["open_issues_count"],
      license_key: data.dig("license", "key"),
      license_name: data.dig("license", "name"),
      license_spdx_id: data.dig("license", "spdx_id"),
      license_url: data.dig("license", "url"),
      license_node_id: data.dig("license", "node_id"),
      allow_forking: data["allow_forking"],
      is_template: data["is_template"],
      web_commit_signoff_required: data["web_commit_signoff_required"],
      topics: data["topics"],
      visibility: data["visibility"],
      forks: data["forks"],
      open_issues: data["open_issues"],
      watchers: data["watchers"],
      default_branch: data["default_branch"],
      temp_clone_token: data["temp_clone_token"],
      network_count: data["network_count"],
      subscribers_count: data["subscribers_count"]
    }
  end
end
